name = "cuTile"
uuid = "0dea8319-8c4a-4662-a73d-20234d115b9a"
authors = ["Tim Besard <tim.besard@gmail.com>"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
